package com.example.musicrec.service.admin;

import com.example.musicrec.domain.Recommendation;
import com.example.musicrec.domain.Track;
import com.example.musicrec.domain.User;
import com.example.musicrec.exception.BadRequestException;
import com.example.musicrec.repository.RecommendationRepository;
import com.example.musicrec.repository.TrackRepository;
import com.example.musicrec.repository.UserRepository;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.Data;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Optional: import recommendations generated by Python into DB.
 *
 * Integration point:
 * - python can write a JSON array:
 *   [{ "userId":"...", "trackId":"...", "score":0.123, "rank":1, "modelVersion":"v1" }, ...]
 */
@Service
@RequiredArgsConstructor
public class RecommendationImportService {

    private final RecommendationRepository recommendationRepository;
    private final UserRepository userRepository;
    private final TrackRepository trackRepository;
    private final ObjectMapper objectMapper;

    public int importFromPath(String jsonPath) {
        try {
            Path p = Path.of(jsonPath).toAbsolutePath().normalize();
            if (!Files.exists(p)) {
                throw new BadRequestException("Recommendations file not found: " + p);
            }

            List<Item> items = objectMapper.readValue(Files.readString(p), new TypeReference<>() {});
            int count = 0;

            for (Item item : items) {
                UUID userId = UUID.fromString(item.userId);
                UUID trackId = UUID.fromString(item.trackId);

                User user = userRepository.findById(userId)
                        .orElseThrow(() -> new BadRequestException("User not found: " + userId));
                Track track = trackRepository.findById(trackId)
                        .orElseThrow(() -> new BadRequestException("Track not found: " + trackId));

                Recommendation r = new Recommendation();
                r.setUser(user);
                r.setTrack(track);
                r.setScore(item.score);
                r.setRank(item.rank);
                r.setModelVersion(item.modelVersion);
                r.setGeneratedAt(item.generatedAt != null ? Instant.parse(item.generatedAt) : Instant.now());

                recommendationRepository.save(r);
                count++;
            }

            return count;
        } catch (BadRequestException e) {
            throw e;
        } catch (Exception e) {
            throw new BadRequestException("Failed to import recommendations: " + e.getMessage());
        }
    }

    @Data
    private static class Item {
        public String userId;
        public String trackId;
        public double score;
        public Integer rank;
        public String modelVersion;
        public String generatedAt; // ISO instant
    }
}
