-- Initial schema for music recommendation backend
-- UUIDs are generated by the application (no DB-side UUID generator required).

CREATE TABLE IF NOT EXISTS app_user (
                                        id uuid PRIMARY KEY,
                                        display_name text NOT NULL,
                                        role text NOT NULL,
                                        created_at timestamptz NOT NULL,
                                        updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS track (
                                     id uuid PRIMARY KEY,
                                     title text NOT NULL,
                                     artist text,
                                     album text,
                                     original_genre text,
                                     duration_seconds integer,
                                     audio_key text NOT NULL,
                                     audio_original_name text,
                                     audio_content_type text,
                                     audio_size_bytes bigint,
                                     metadata_text text,
                                     created_at timestamptz NOT NULL,
                                     updated_at timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_track_created_at ON track(created_at DESC);

CREATE TABLE IF NOT EXISTS track_feature (
                                             id uuid PRIMARY KEY,
                                             track_id uuid NOT NULL REFERENCES track(id) ON DELETE CASCADE,
    feature_key text NOT NULL,
    value_string text,
    value_number double precision,
    confidence double precision,
    source text NOT NULL,
    extracted_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT uq_track_feature UNIQUE(track_id, feature_key)
    );

CREATE INDEX IF NOT EXISTS idx_track_feature_track ON track_feature(track_id);

CREATE TABLE IF NOT EXISTS interaction (
                                           id uuid PRIMARY KEY,
                                           user_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    track_id uuid NOT NULL REFERENCES track(id) ON DELETE CASCADE,
    type text NOT NULL,
    event_time timestamptz NOT NULL,
    position_ms bigint,
    metadata_text text,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_interaction_user_time ON interaction(user_id, event_time DESC);
CREATE INDEX IF NOT EXISTS idx_interaction_track_time ON interaction(track_id, event_time DESC);

CREATE TABLE IF NOT EXISTS rating (
                                      id uuid PRIMARY KEY,
                                      user_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    track_id uuid NOT NULL REFERENCES track(id) ON DELETE CASCADE,
    value integer NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT uq_rating UNIQUE(user_id, track_id)
    );

CREATE INDEX IF NOT EXISTS idx_rating_user ON rating(user_id);

CREATE TABLE IF NOT EXISTS recommendation (
                                              id uuid PRIMARY KEY,
                                              user_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    track_id uuid NOT NULL REFERENCES track(id) ON DELETE CASCADE,
    score double precision NOT NULL,
    rank integer,
    model_version text,
    generated_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_reco_user_generated ON recommendation(user_id, generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_reco_user_score ON recommendation(user_id, score DESC);
